language: python
python:
- '2.7'
install:
- python setup.py install
- pip install -r test-requirements.txt
script: nosetests tests.unit
deploy:
  provider: pypi
  on:
    tags: true
  password:
    secure: F64XCTe9p1jvMHbuZGSzSYGnp9CTWCg+Waq/rtpJvlXzc/mt1q7Pks1bCBJiE3Rc2OB8gXMWtBNwwCK8mI8KvhVCwhgbBF9FF55bDGQKyr+iI461tkOKmZQjzisBJxFuT++r0DjjYV3G6RP7lvnqXMYj1TrhNL/jDA4fLBDc1WoJ2trTdONFSYr1lYkk010RMdhLwFUWHdeYBLyv1dAyStXkqVvV1lLN4+RGSNwQtqBAH/KmWY9wPYRg83CEOhpYpboD+5THj7Kl+eSF1r5z93WmK6h2Vbl6zeEVrZPtpWFUawEFqrAv3Ic5ZB3SokhvXgPa1aTorJzrq0gmc/BOX2/OCu6HllnYyHrhjo7GdBLLxRoXG049VlDxA8ZdwtR6jPyX5oQ2iZvUOeuJ7jHzoYSQAjeZqioc2xzacVhbrNHPOdH1xyB1H+8Sq09WajkgJey7xZlvu534m0rihsfOF1NzB8zBn2VgBu0mZwCvnOtwhPeyMXYfczGIDpzioVX4++IJ2MkJFLf34ARu64zVUHyVcNm9PM6YSdwFHI2aCxylYwZaNpM+9hg21ms0oNQ2wTlvsMVoA8UrHnWHqdGJ0Yv1B+QobinaSEPFsjsS6uriP/QIiAM4XigLlxNQiNH93eBH3um/Xm0pb7CQ1s1tzTNMeyF5fIMgBgc111A1eqE=
  user:
    secure: CDod5T0sQdfLv1pLwqzwngtOcOplSfRicXomOd9wqnkcfNTCyumRmj/YvMUvvlh33XH7SMfKZSO4+rh411/NUa5DTkoZqfeRB50/048QxTp5rZ2PW6qXOLYOOVDkjxcRTreA2Ltn5J9YSfoqxdcqeEf4X2tC8fvNQYW3bFFiTis7JZDijEIINoz25+aICTYdjdBIy/MvD1IA1JkDsxa2xrmVIajqZxKJRNbxkVLOl5R+w2nUFlmPbuwpE5lAhjDVH6im9CWknMyij4oQyB/4GfMN/C224u/d0qbhXobq/8dT9zCNj/XHbdP5M87gy5gB6/iLOENAOodRap/AtgW8A8InRTLE7b1+O43pTSuqI6H2jOyekv3da3GKvcF9q1eS+pPK8En9dJiZPKbjSg63v6gFeDd/jw/lJ0G4i7lK2s8TgrieRtvRUynzMDudkGzS9VQxfES/mrG0LGK/oRgc/xKpCzCW7Gr9vAFyLQxhViGqqTUIjyyV8pygNsFcCuk98AdWDtv2+EiHHN6iqVZ+koySQxYFAcnFJcMLUWAfgnokJzOpYjYA1iim94PlbHr+8AXFykARfHF+uZYCjHrg/k06c4gEm+e0sqTYxucI24TGWob/7M6tm3N37bsOFITJZPog2FFwkHBSgxjUJ98Mu323YPp+0Umq6PWSWMSQO90=
